[package]
name = "parsehtml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

scraper = "0.17.1"
base64 = "0.21.4"