#!/bin/bash
function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }

in_raw="$(cat|grep -oE 'html=([^&]+)'|sed 's/^html=//g')" # get html parameter
in_decode=$(urldecode "$in_raw") # url decode parameter

echo "content-type: text/plain"
echo ""
echo
CC=gcc LANG=C.UTF-8 HOME=/app elixir /app/floki.exs "$in_decode"
CC=gcc LANG=C.UTF-8 HOME=/app elixir /app/floki_html5ever.exs "$in_decode"
CC=gcc LANG=C.UTF-8 HOME=/app elixir /app/floki_fast_html.exs "$in_decode"